version: "3"
services:
  mongo_1:
    container_name: mongo_1
    image: mongo
    ports:
      - 27011:27011
    volumes:
      - ./docker_volume/mongo_1:/data/db
    command:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--replSet",
        "rs0",
        "--port",
        "27011",
      ]
    networks:
      static-network:
        ipv4_address: "$MONGO_1_IP"
    links:
      - "mongo_2:mongo_2"
      - "mongo_3:mongo_3"

  mongo_2:
    container_name: mongo_2
    image: mongo
    ports:
      - 27012:27012
    volumes:
      - ./docker_volume/mongo_2:/data/db
    command:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--replSet",
        "rs0",
        "--port",
        "27012",
      ]
    networks:
      static-network:
        ipv4_address: "$MONGO_2_IP"
    links:
      - "mongo_3:mongo_3"

  mongo_3:
    container_name: mongo_3
    image: mongo
    ports:
      - 27013:27013
    volumes:
      - ./docker_volume/mongo_3:/data/db
    command:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--replSet",
        "rs0",
        "--port",
        "27013",
      ]
    networks:
      static-network:
        ipv4_address: "$MONGO_3_IP"

  pg_main_db:
    image: postgres
    container_name: pg_main_db
    ports:
      - 5431:5431
    volumes:
      - ./docker_volume/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
    networks:
      static-network:
        ipv4_address: "$POSTGRES_IP"

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          #docker-compose v3+ do not use ip_range
          ip_range: 172.28.5.0/24
